esphome:
  name: officerfid

esp8266:
  board: d1_mini_lite

wifi:
  ssid: "Your-WiFi-SSID"
  password: "Your-WiFi-Password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Officerfid Fallback Hotspot"
    password: "Your-desired-hotspot-password"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

wiegand:
  - id: rfidreader
    d0: D5
    d1: D6
    on_tag:
      - lambda: ESP_LOGI("TAG", "received tag %s", x.c_str());
      - homeassistant.tag_scanned: !lambda 'return x;'
